const category_bar = [
  "Bar",
  "Beer Bar",
  "Beer Garden",
  "Champagne Bar",
  "Cocktail Bar",
  "Dive Bar",
  "Gay Bar",
  "Hookah Lounge",
  "Hotel Bar",
  "Irish Pub",
  "Lounge",
  "Pub",
  "Sake Bar",
  "Speakeasy",
  "Sports Bar",
  "Tiki Bar",
  "Whisky Bar",
  "Wine Bar",
  "Dance & Night Club"
];

const category_cafe = [
  "Cafe",
  "Dessert Shop",
  "Coffee Shop",
  "Pet Cafe",
  "Tea Room",
  "Donut Shop",
  "Chocolate Shop",
  "Cupcake Shop",
  "Frozen Yogurt Shop",
  "Gelato Shop",
  "Ice Cream Shop",
  "Shaved Ice Shop",
  "Smoothie & Juice Bar"
];

const category_restaurant = [
  "Food & Beverage",
  "Bagel Shop",
  "Bakery",
  "Wholesale Bakery",
  "Bottled Water Company",
  "Brewery",
  "Bubble Tea Shop",
  "Butcher Shop",
  "Cafeteria",
  "Caterer",
  "Cheese Shop",
  "Convenience Store",
  "Deli",
  "Distillery",
  "Foodservice Distributor",
  "Food Consultant",
  "Food Delivery Service",
  "Food Stand",
  "Food Truck",
  "Food Wholesaler",
  "Meat Wholesaler",
  "Restaurant Wholesaler",
  "Personal Chef",
  "Restaurant",
  "Afghani Restaurant",
  "African Restaurant",
  "Ethiopian Restaurant",
  "Nigerian Restaurant",
  "Senegalese Restaurant",
  "South African Restaurant",
  "American Restaurant",
  "Arabian Restaurant",
  "Asian Restaurant",
  "Asian Fusion Restaurant",
  "Burmese Restaurant",
  "Cambodian Restaurant",
  "Chinese Restaurant",
  "Anhui Restaurant",
  "Beijing Restaurant",
  "Cantonese Restaurant",
  "Dim Sum Restaurant",
  "Dongbei Restaurant",
  "Fujian Restaurant",
  "Guizhou Restaurant",
  "Hainan Restaurant",
  "Henan Restaurant",
  "Hong Kong Restaurant",
  "Hot Pot Restaurant",
  "Huaiyang Restaurant",
  "Hubei Restaurant",
  "Hunan Restaurant",
  "Imperial Restaurant",
  "Jiangsu Restaurant",
  "Jiangxi Restaurant",
  "Macanese Restaurant",
  "Manchu Restaurant",
  "Shaanxi Restaurant",
  "Shandong Restaurant",
  "Shanghainese Restaurant",
  "Shanxi Restaurant",
  "Szechuan/Sichuan Restaurant",
  "Tianjin Restaurant",
  "Xinjiang Restaurant",
  "Yunnan Restaurant",
  "Zhejiang Restaurant",
  "Filipino Restaurant",
  "Indo Chinese Restaurant",
  "Indonesian Restaurant",
  "Acehnese Restaurant",
  "Balinese Restaurant",
  "Betawinese Restaurant",
  "Javanese Restaurant",
  "Manadonese Restaurant",
  "Padangnese Restaurant",
  "Sundanese Restaurant",
  "Japanese Restaurant",
  "Donburi Restaurant",
  "Kaiseki Restaurant",
  "Kushikatsu Restaurant",
  "Monjayaki Restaurant",
  "Nabe Restaurant",
  "Okonomiyaki Restaurant",
  "Ramen Restaurant",
  "Shabu Shabu Restaurant",
  "Soba Restaurant",
  "Sukiyaki Restaurant",
  "Sushi Restaurant",
  "Takoyaki Restaurant",
  "Tempura Restaurant",
  "Teppanyaki Restaurant",
  "Tonkatsu Restaurant",
  "Udon Restaurant",
  "Unagi Restaurant",
  "Wagashi Restaurant",
  "Yakiniku Restaurant",
  "Yakitori Restaurant",
  "Yoshoku Restaurant",
  "Korean Restaurant",
  "Bossam/Jokbal Restaurant",
  "Bunsik Restaurant",

  "Gukbap Restaurant",
  "Janguh Restaurant",
  "Samgyetang Restaurant",
  "Malaysian Restaurant",
  "Mongolian Restaurant",
  "Noodle House",
  "Singaporean Restaurant",
  "Taiwanese Restaurant",
  "Thai Restaurant",
  "Vietnamese Restaurant",
  "Pho Restaurant",
  "Australian Restaurant",
  "Austrian Restaurant",
  "Bar & Grill",
  "Barbecue Restaurant",
  "Basque Restaurant",
  "Belgian Restaurant",
  "Breakfast & Brunch Restaurant",
  "British Restaurant",
  "Buffet Restaurant",
  "Burger Restaurant",
  "Cajun & Creole Restaurant",
  "Canadian Restaurant",
  "Caribbean Restaurant",
  "Dominican Restaurant",
  "Haitian Restaurant",
  "Jamaican Restaurant",
  "Trinidadian Restaurant",
  "Catalan Restaurant",
  "Chicken Joint",
  "Comfort Food Restaurant",
  "Continental Restaurant",
  "Crêperie",
  "Czech Restaurant",
  "Diner",
  "Drive In Restaurant",
  "Eastern European Restaurant",
  "Belarusian Restaurant",
  "Bulgarian Restaurant",
  "Romanian Restaurant",
  "Tatar Restaurant",
  "Egyptian Restaurant",
  "European Restaurant",
  "Family Style Restaurant",
  "Fast Food Restaurant",
  "Fish & Chips Restaurant",
  "Fondue Restaurant",
  "French Restaurant",
  "Gastropub",
  "German Restaurant",
  "Baden Restaurant",
  "Bavarian Restaurant",
  "Hessian Restaurant",
  "Palatine Restaurant",
  "Saxon Restaurant",
  "Swabian Restaurant",
  "Gluten-Free Restaurant",
  "Halal Restaurant",
  "Hawaiian Restaurant",
  "Health Food Restaurant",
  "Himalayan Restaurant",
  "Hot Dog Joint",
  "Hungarian Restaurant",
  "Iberian Restaurant",
  "Indian Restaurant",
  "Andhra Restaurant",
  "Awadhi Restaurant",
  "Bengali/Bangladeshi Restaurant",
  "Chaat Place",
  "Chettinad Restaurant",
  "Dhaba Restaurant",
  "Dosa Restaurant",
  "Goan Restaurant",
  "Gujarati Restaurant",
  "Hyderabadi Restaurant",
  "Indian Chinese Restaurant",
  "Irani Restaurant",
  "Jain Restaurant",
  "Karnataka Restaurant",
  "Kashmiri Restaurant",
  "Kerala Restaurant",
  "Maharashtrian Restaurant",
  "Mughalai Restaurant",
  "North Indian Restaurant",
  "Parsi Restaurant",
  "Punjabi Restaurant",
  "Rajasthani Restaurant",
  "South Indian Restaurant",
  "Tamilian Restaurant",
  "Udupi Restaurant",
  "Uttar Pradesh Restaurant",
  "Irish Restaurant",
  "Italian Restaurant",
  "Abruzzo Restaurant",
  "Aosta Restaurant",
  "Basilicata Restaurant",
  "Calabrian Restaurant",
  "Emilia Romagna Restaurant",
  "Friuli Venezia Giulia Restaurant",
  "Ligurian Restaurant",
  "Lombard Restaurant",
  "Marche Restaurant",
  "Molise Restaurant",
  "Neapolitan Restaurant",
  "Piedmont Restaurant",
  "Puglia Restaurant",
  "Roman Restaurant",
  "Sardinian Restaurant",
  "Sicilian Restaurant",
  "South Tyrolean Restaurant",
  "Trentino Alto Adige Restaurant",
  "Tuscan Restaurant",
  "Umbrian Restaurant",
  "Venetian Restaurant",
  "Kosher Restaurant",
  "Latin American Restaurant",
  "Argentinian Restaurant",
  "Belizean Restaurant",
  "Bolivian Restaurant",
  "Brazilian Restaurant",
  "Chilean Restaurant",
  "Colombian Restaurant",
  "Costa Rican Restaurant",
  "Cuban Restaurant",
  "Ecuadorian Restaurant",
  "Guatemalan Restaurant",
  "Honduran Restaurant",
  "Mexican Restaurant",
  "Tex-Mex Restaurant",
  "Nicaraguan Restaurant",
  "Panamanian Restaurant",
  "Paraguayan Restaurant",
  "Peruvian Restaurant",
  "Puerto Rican Restaurant",
  "Salvadoran Restaurant",
  "Uruguayan Restaurant",
  "Venezuelan Restaurant",
  "Live & Raw Food Restaurant",
  "Mediterranean Restaurant",
  "Greek Restaurant",
  "Middle Eastern Restaurant",
  "Armenian Restaurant",
  "Azerbaijani Restaurant",
  "Georgian Restaurant",
  "Israeli Restaurant",
  "Kurdish Restaurant",
  "Lebanese Restaurant",
  "Persian/Iranian Restaurant",
  "Syrian Restaurant",
  "Turkish Restaurant",
  "Kebab Shop",
  "Modern European Restaurant",
  "Molecular Gastronomy Restaurant",
  "Moroccan Restaurant",
  "Nepalese Restaurant",
  "New American Restaurant",
  "Pakistani Restaurant",
  "Pizza Place",
  "Polish Restaurant",
  "Polynesian Restaurant",
  "Portuguese Restaurant",
  "Russian Restaurant",
  "Salad Bar",
  "Scandinavian Restaurant",
  "Scottish Restaurant",
  "Seafood Restaurant",
  "Slovakian Restaurant",
  "Soul Food Restaurant",
  "Soup Restaurant",
  "Southern Restaurant",
  "Southwestern Restaurant",
  "Spanish Restaurant",
  "Sri Lankan Restaurant",
  "Steakhouse",
  "Swiss Restaurant",
  "Tapas Bar & Restaurant",
  "Theme Restaurant",
  "Ukrainian Restaurant",
  "Uzbek Restaurant",
  "Vegetarian/Vegan Restaurant",
  "Sandwich Shop"
];

const category_geographical_places = [
  "Locality",
  "Cemetary",
  "Borough",
  "Ocean",
  "Island",
  "Pet Cemetery",
  "City",
  "City",
  "Congressional District",
  "Continental Region",
  "Country",
  "County",
  "Designated Market Area",
  "Geo Entity",
  "Harbor",
  "Large Geo Area",
  "Medium Geo Area",
  "Metro Area",
  "Neighborhood",
  "Port",
  "Postal Code",
  "Province",
  "Region",
  "Shopping District",
  "Small Geo Area",
  "State",
  "Subcity",
  "Subneighborhood",
  "Time zone",
  "Township",
  "Village",
  "Continent"
];

const category_hotel = [
  "Hotel",
  "Hotel & Lodging",
  "Hotel Services Company",
  "Bed and Breakfast",
  "Cabin",
  "Campground",
  "Cottage",
  "Hostel",
  "Inn",
  "Lodge",
  "Motel",
  "RV Park",
  "Service Apartments",
  "Beach Resort",
  "Hotel Resort",
  "Vacation Home Rental"
];

const category_other = [
  "TypeAhead",
  "Website",
  "Interest",
  "Community Organization",
  "Media",
  "Books & Magazines",
  "Media Restoration Service",
  "Music",
  "TV & Movies",
  "Public Figure",
  "Designer",
  "Government Official",
  "Video Creator",
  "Businesses",
  "Advertising/Marketing",
  "Commercial & Industrial",
  "Environmental Service",
  "Forestry & Logging",
  "Manufacturer/Supplier",
  "Metal & Steel Company",
  "Mining Company",
  "Plastic Company",
  "Education",
  "School",
  "College & University",
  "Finance",
  "Bank",
  "Financial Service",
  "Insurance Company",
  "Investing Service",
  "Investment Management Company",
  "Legal",
  "Lawyer & Law Firm",
  "Legal Service",
  "Local Service",
  "Design & Fashion",
  "In-Home Service",
  "Party Entertainment Service",
  "Pet Service",
  "Photography Videography",
  "Printing Service",
  "Moving & Storage Service",
  "Business Service",
  "Employment Agency",
  "Event Planner",
  "Home Improvement",
  "Appliance Repair Service",
  "Media/News Company",
  "Medical & Health",
  "Dentist & Dental Office",
  "Medical Center",
  "Medical Service",
  "Alternative & Holistic Health Service",
  "Pharmacy / Drugstore",
  "Therapist",
  "Doctor",
  "Public & Government Service",
  "Community Center",
  "Public Utility Company",
  "Science, Technology & Engineering",
  "Chemical Company",
  "Information Technology Company",
  "Telecommunications Company",
  "Automotive Service",
  "Real Estate",
  "Travel & Transportation",
  "Transit Hub",
  "Travel Service",
  "Non-Business Places",
  "Sports Team",
  "Sport",
  "Anatomical Structure",
  "Animal",
  "Animal Breed",
  "Coming of Age",
  "Competition",
  "Cultural Heritage",
  "Drink",
  "Education/Work Status",
  "Field of Study",
  "High School Status",
  "Holiday",
  "Life Event",
  "Local Business Type",
  "Medical Procedure",
  "Organization/Institution Type",
  "Pet Tricks",
  "Public Figure Type",
  "Concentration or Major",
  "Degree",
  "Work Position Type",
  "Year",
  "University Status",
  "Work Position",
  "Work Project",
  "Work Status",
  "Feed for Workplace",
  "Arts & Humanities Website",
  "Business & Economy Website",
  "Computers & Internet Website",
  "E-commerce Website",
  "Education Website",
  "Entertainment Website",
  "Food Website",
  "Government Website",
  "Health & Wellness Website",
  "Home & Garden Website",
  "Teens & Kids Website",
  "News & Media Website",
  "Personal Blog",
  "Recreation & Sports Website",
  "Reference Website",
  "Regional Website",
  "Science Website",
  "Society & Culture Website",
  "Local & Travel Website",
  "Literary Arts",
  "Performance Art",
  "Performing Arts",
  "Science",
  "Sports",
  "Visual Arts",
  "Armed Forces",
  "Charity Organization",
  "Country Club / Clubhouse",
  "Community Service",
  "Environmental Conservation Organization",
  "Government Organization",
  "Labor Union",
  "Political Organization",
  "Political Party",
  "Private Members Club",
  "Religious Organization",
  "Social Club",
  "Sorority & Fraternity",
  "Sports Club",
  "Youth Organization",
  "Art",
  "Article",
  "Book",
  "Book Genre",
  "Book Series",
  "Magazine",
  "Newspaper",
  "Concert Tour",
  "Art Restoration Service",
  "Show",
  "Album",
  "Choir",
  "Music Award",
  "Music Chart",
  "Musical Genre",
  "Music Video",
  "Playlist",
  "Podcast",
  "Record Label",
  "Song",
  "Symphony",
  "Theatrical Play",
  "Theatrical Productions",
  "Episode",
  "Movie",
  "Movie Character",
  "Movie Genre",
  "TV Channel",
  "TV",
  "TV Genre",
  "TV/Movie Award",
  "TV Network",
  "One-Time TV Program",
  "TV Season",
  "TV Show",
  "Video",
  "Actor",
  "Artist",
  "Athlete",
  "Author",
  "Band",
  "Musician/Band",
  "Blogger",
  "Chef",
  "Comedian",
  "Dancer",
  "Fashion Designer",
  "Digital Creator",
  "Entrepreneur",
  "Fashion Model",
  "Film Director",
  "Fitness Model",
  "Monarch",
  "Political Candidate",
  "Politician",
  "Editor",
  "Journalist",
  "Motivational Speaker",
  "Writer",
  "Musician",
  "News Personality",
  "Orchestra",
  "Producer",
  "Gamer",
  "Scientist",
  "Spiritual Leader",
  "Sports Promoter",
  "Talent Agent",
  "Gaming Video Creator",
  "Advertising Agency",
  "Copywriting Service",
  "Internet Marketing Service",
  "Market Research Consultant",
  "Marketing Agency",
  "Media Agency",
  "Merchandising Service",
  "Public Relations Agency",
  "Social Media Agency",
  "Telemarketing Service",
  "Automation Service",
  "Commercial & Industrial Equipment Supplier",
  "Environmental Consultant",
  "Geologic Service",
  "Occupational Safety and Health Service",
  "Recycling Center",
  "Forestry Service",
  "Logging Contractor",
  "Industrial Company",
  "Inventory Control Service",
  "Aircraft Manufacturer",
  "Appliance Manufacturer",
  "Glass Manufacturer",
  "Machine Shop",
  "Mattress Manufacturer",
  "Metal Fabricator",
  "Metal Plating Service Company",
  "Metal Supplier",
  "Granite & Marble Supplier",
  "Plastic Fabricator",
  "Plastic Manufacturer",
  "Tobacco Company",
  "Archaeological Service",
  "Academic Camp",
  "Educational Consultant",
  "Educational Research Center",
  "Art School",
  "Day Care",
  "Elementary School",
  "High School",
  "Junior High School",
  "Medical School",
  "Middle School",
  "Performing Arts School",
  "Preschool",
  "Private School",
  "Public School",
  "Religious School",
  "Test Preparation Center",
  "Tutor/Teacher",
  "Community College",
  "Commercial Bank",
  "Credit Union",
  "Investment Bank",
  "Retail Bank",
  "Accountant",
  "Bank Equipment & Service",
  "Franchise Broker",
  "Cash Advance Service",
  "Collection Agency",
  "Credit Counseling Service",
  "Currency Exchange",
  "Financial Aid Service",
  "Financial Consultant",
  "Financial Planner",
  "Loan Service",
  "Tax Preparation Service",
  "Insurance Agent",
  "Insurance Broker",
  "Brokerage Firm",
  "Hedge Fund",
  "Bankruptcy Lawyer",
  "Contract Lawyer",
  "Corporate Lawyer",
  "Criminal Lawyer",
  "Divorce & Family Lawyer",
  "DUI Lawyer",
  "Entertainment Lawyer",
  "General Litigation",
  "Immigration Lawyer",
  "Internet Lawyer",
  "Juvenile Lawyer",
  "Labor & Employment Lawyer",
  "Landlord & Tenant Lawyer",
  "Malpractice Lawyer",
  "Medical Lawyer",
  "Military Lawyer",
  "Intellectual Property Lawyer",
  "Personal Injury Lawyer",
  "Property Lawyer",
  "Real Estate Lawyer",
  "Tax Lawyer",
  "Estate Planning Lawyer",
  "Bail Bondsmen",
  "Lobbyist",
  "Notary Public",
  "Private Investigator",
  "Process Service",
  "Adoption Service",
  "Astrologist",
  "Bicycle Repair Service",
  "Bottled Water Supplier",
  "Career Counselor",
  "Computer Repair Service",
  "Dating Service",
  "Modeling Agency",
  "Dry Cleaner",
  "Funeral Service & Cemetery",
  "Genealogist",
  "Babysitter",
  "Child Care Service",
  "Cleaning Service",
  "House Sitter",
  "Maid & Butler",
  "Nanny",
  "Internet Cafe",
  "Junkyard",
  "Laundromat",
  "Locksmith",
  "Parking Garage / Lot",
  "Adult Entertainment Service",
  "DJ",
  "Kids Entertainment Service",
  "Magician",
  "Animal Shelter",
  "Dog Day Care Center",
  "Dog Trainer",
  "Dog Walker",
  "Horse Trainer",
  "Kennel",
  "Livery Stable",
  "Pet Adoption Service",
  "Pet Breeder",
  "Pet Groomer",
  "Pet Sitter",
  "Taxidermist",
  "Veterinarian",
  "Amateur Photographer",
  "Event Photographer",
  "Photo Booth Service",
  "Photographer",
  "Event Videographer",
  "Screen Printing & Embroidery",
  "Signs & Banner Service",
  "Home Mover",
  "Self-Storage Facility",
  "Storage Facility",
  "Business Consultant",
  "Business Supply Service",
  "Cargo & Freight Company",
  "Consulting Agency",
  "Recruiter",
  "Franchising Service",
  "Graphic Designer",
  "Hospitality Service",
  "Janitorial Service",
  "Management Service",
  "Security Guard Service",
  "Personal Assistant",
  "Personal Coach",
  "Secretarial Service",
  "Shipping Supply & Service",
  "Shredding Service",
  "Translator",
  "Uniform Supplier",
  "Vending Machine Sales & Service",
  "Web Designer",
  "Bartending Service",
  "Wedding Planning Service",
  "Heating, Ventilating & Air Conditioning Service",
  "Refrigeration Service",
  "Water Heater Installation & Repair Service",
  "Architectural Designer",
  "Carpenter",
  "Carpet Cleaner",
  "Chimney Sweeper",
  "Concrete Contractor",
  "Construction Company",
  "Contractor",
  "Damage Restoration Service",
  "Deck & Patio Builder",
  "Electrician",
  "Elevator Service",
  "Demolition & Excavation Company",
  "Fence & Gate Contractor",
  "Fire Protection Service",
  "Furniture Repair & Upholstery Service",
  "Garage Door Service",
  "Gardener",
  "Glass Service",
  "Gutter Cleaning Service",
  "Handyman",
  "Home Security Company",
  "Home Window Service",
  "House Painting",
  "Interior Design Studio",
  "Kitchen & Bath Contractor",
  "Landscape Company",
  "Lumber Yard",
  "Masonry Contractor",
  "Paving & Asphalt Service",
  "Pest Control Service",
  "Plumbing Service",
  "Portable Building Service",
  "Portable Toilet Rentals",
  "Powder Coating Service",
  "Roofing Service",
  "Sandblasting Service",
  "Septic Tank Service",
  "Sewer Service",
  "Solar Energy Service",
  "Swimming Pool Cleaner",
  "Swimming Pool & Hot Tub Service",
  "Tiling Service",
  "Tree Cutting Service",
  "Vinyl Siding Company",
  "Water Treatment Service",
  "Well Water Drilling Service",
  "Window Installation Service",
  "Weight Loss Center",
  "Writing Service",
  "Animation Studio",
  "Book & Magazine Distributor",
  "Broadcasting & Media Production Company",
  "Game Publisher",
  "Movie/Television Studio",
  "Music Production Studio",
  "Radio Station",
  "Social Media Company",
  "Publisher",
  "Cosmetic Dentist",
  "Endodontist",
  "General Dentist",
  "Oral Surgeon",
  "Orthodontist",
  "Pediatric Dentist",
  "Periodontist",
  "Prosthodontist",
  "Teeth Whitening Service",
  "AIDS Resource Center",
  "Blood Bank",
  "Crisis Prevention Center",
  "Diagnostic Center",
  "Dialysis Clinic",
  "Emergency Room",
  "Family Medicine Practice",
  "Halfway House",
  "Hospice",
  "Hospital",
  "Maternity Clinic",
  "Medical Lab",
  "Nursing Home",
  "Pregnancy Care Center",
  "Retirement & Assisted Living Facility",
  "STD Testing Center",
  "Surgical Center",
  "Women's Health Clinic",
  "Medical Device Company",
  "Medical Equipment Manufacturer",
  "Medical Equipment Supplier",
  "Medical Research Center",
  "Abortion Service",
  "Addiction Resources Center",
  "Addiction Treatment Center",
  "Alcohol Addiction Treatment Center",
  "Drug Addiction Treatment Center",
  "Tobacco Cessation Treatment Center",
  "Acupuncturist",
  "Chiropractor",
  "Naturopath",
  "Nutritionist",
  "Reflexologist",
  "Emergency Rescue Service",
  "Mental Health Service",
  "Disability Service",
  "Healthcare Administrator",
  "Home Health Care Service",
  "Nursing Agency",
  "Orthotics & Prosthetics Service",
  "Reproductive Service",
  "Safety & First Aid Service",
  "Optician",
  "Pharmaceutical Company",
  "Medical Supply Store",
  "Vitamin Supplement Shop",
  "Counselor",
  "Family Therapist",
  "Marriage Therapist",
  "Occupational Therapist",
  "Physical Therapist",
  "Psychotherapist",
  "Sex Therapist",
  "Speech Pathologist",
  "Speech Therapist",
  "Sport Psychologist",
  "Allergist",
  "Anesthesiologist",
  "Audiologist",
  "Cardiologist",
  "Dermatologist",
  "Endocrinologist",
  "Family Doctor",
  "Fertility Doctor",
  "Gastroenterologist",
  "Gerontologist",
  "Internist (Internal Medicine)",
  "Lasik/Laser Eye Surgeon",
  "Nephrologist",
  "Neurologist",
  "Neurosurgeon",
  "Obstetrician-Gynecologist (OBGYN)",
  "Oncologist",
  "Ophthalmologist",
  "Optometrist",
  "Orthopedist",
  "Osteopathic Doctor",
  "Otolaryngologist (ENT)",
  "Pediatrician",
  "Plastic Surgeon",
  "Podiatrist",
  "Proctologist",
  "Psychiatrist",
  "Psychologist",
  "Pulmonologist",
  "Radiologist",
  "Rheumatologist",
  "Surgeon",
  "Urologist",
  "Non-Governmental Organization (NGO)",
  "Nonprofit Organization",
  "Automotive Registration Center",
  "Child Protective Service",
  "Senior Center",
  "Defense Company",
  "DMV",
  "Food Bank",
  "Housing & Homeless Shelter",
  "Law Enforcement Agency",
  "Passport & Visa Service",
  "Public Service",
  "Electric Utility Provider",
  "Energy Company",
  "Internet Service Provider",
  "Television Service Provider",
  "Water Utility Company",
  "Social Service",
  "Library",
  "Waste Management Company",
  "Aerospace Company",
  "Biotechnology Company",
  "Gas & Chemical Service",
  "Petroleum Service",
  "Engineering Service",
  "Computer Company",
  "Electronics Company",
  "Internet Company",
  "Software Company",
  "Cable & Satellite Company",
  "Robotics Company",
  "Solar Energy Company",
  "Structural Engineer",
  "Surveyor",
  "Automotive Body Shop",
  "Auto Detailing Service",
  "Automotive Glass Service",
  "Automotive Leasing Service",
  "Automotive Consultant",
  "Automotive Customization Shop",
  "Automotive Repair Shop",
  "Automotive Restoration Service",
  "Automotive Shipping Service",
  "Automotive Storage Facility",
  "Automotive Wheel Polishing Service",
  "Boat Service",
  "Car Wash",
  "Emergency Roadside Service",
  "Smog Emissions Check Station",
  "Gas Station",
  "Marine Service Station",
  "Motorcycle Repair Shop",
  "Oil Lube & Filter Service",
  "RV Repair Shop",
  "Tire Dealer & Repair Shop",
  "Towing Service",
  "Truck Repair Shop",
  "Wheel & Rim Repair Service",
  "Automotive Window Tinting Service",
  "Commercial Real Estate Agency",
  "Escrow Service",
  "Home Inspector",
  "Home Staging Service",
  "Housing Assistance Service",
  "Mobile Home Park",
  "Mobile Home Dealer",
  "Mortgage Brokers",
  "Property Management Company",
  "Real Estate Agent",
  "Real Estate Appraiser",
  "Real Estate Company",
  "Real Estate Developer",
  "Real Estate Investment Firm",
  "Real Estate Service",
  "Real Estate Title & Development",
  "Airline Company",
  "Airline Industry Service",
  "Railroad Company",
  "Airport Gate",
  "Airport Lounge",
  "Airport Terminal",
  "Bus Station",
  "Heliport",
  "Seaplane Base",
  "Airport",
  "Transit Stop",
  "Luggage Service",
  "Automated Teller Machine (ATM)",
  "Meeting Room",
  "Cause",
  "Color",
  "Community",
  "Cuisine",
  "Diseases",
  "Editorial/Opinion",
  "Election",
  "Exchange Program",
  "Fan Page",
  "Harmonized Page",
  "Language",
  "Mood",
  "Nationality",
  "University (NCES)",
  "Not a Business",
  "Political Ideology",
  "Profile",
  "Satire/Parody",
  "Course",
  "Sports Season",
  "Surgeries",
  "Ticket Sales",
  "Topic",
  "Amateur Sports Team",
  "Esports Team",
  "Professional Sports Team",
  "School Sports Team"
];

const category_places_to_visit = [
  "Geographical Place",
  "Outdoor Recreation",
  "Park",
  "Public Garden",
  "Recreation Spot",
  "Religious Place of Worship",
  "Church",
  "Landmark & Historical Place",
  "Agriculture",
  "Farm",
  "Event Space",
  "Stadium, Arena & Sports Venue",
  "City Infrastructure",
  "Government Building",
  "Residence",
  "Train Station",
  "Bay",
  "Beach",
  "Cape",
  "Cave",
  "Desert",
  "Fjord/Loch",
  "Glacier",
  "Hot Spring",
  "Pond",
  "Reservoir",
  "Lake",
  "Mountain",
  "River",
  "Volcano",
  "Waterfall",
  "Fairground",
  "Arboretum",
  "Dog Park",
  "Field",
  "National Forest",
  "National Park",
  "Nature Preserve",
  "Picnic Ground",
  "Playground",
  "Public Square / Plaza",
  "State Park",
  "Botanical Garden",
  "Community Garden",
  "Rose Garden",
  "Sculpture Garden",
  "Bike Trail",
  "Diving Spot",
  "Fishing Spot",
  "Hiking Trail",
  "Rock Climbing Spot",
  "Snorkeling Spot",
  "Surfing Spot",
  "Public Toilet",
  "Assemblies of God",
  "Buddhist Temple",
  "African Methodist Episcopal Church",
  "Anglican Church",
  "Apostolic Church",
  "Baptist Church",
  "Catholic Church",
  "Charismatic Church",
  "Christian Church",
  "Christian Science Church",
  "Church of Christ",
  "Church of God",
  "Church of Jesus Christ of Latter-day Saints",
  "Congregational Church",
  "Eastern Orthodox Church",
  "Episcopal Church",
  "Evangelical Church",
  "Full Gospel Church",
  "Holiness Church",
  "Independent Church",
  "Interdenominational Church",
  "Lutheran Church",
  "Mennonite Church",
  "Methodist Church",
  "Nazarene Church",
  "Nondenominational Church",
  "Pentecostal Church",
  "Presbyterian Church",
  "Seventh Day Adventist Church",
  "Convent & Monastery",
  "Hindu Temple",
  "Kingdom Hall",
  "Mission",
  "Mosque",
  "Religious Center",
  "Sikh Temple",
  "Synagogue",
  "Monument",
  "Statue & Fountain",
  "Agricultural Cooperative",
  "Agricultural Service",
  "Dairy Farm",
  "Fish Farm",
  "Livestock Farm",
  "Poultry Farm",
  "Urban Farm",
  "Ballroom",
  "Business Center",
  "Convention Center",
  "Wedding Venue",
  "Cultural Center",
  "Baseball Stadium",
  "Basketball Stadium",
  "Cricket Ground",
  "Football Stadium",
  "Hockey Arena",
  "Rugby Stadium",
  "Soccer Stadium",
  "Tennis Stadium",
  "Track Stadium",
  "Tourist Information Center",
  "Bridge",
  "Canal",
  "Highway",
  "Lighthouse",
  "Marina",
  "Pier",
  "Promenade",
  "Quay",
  "Street",
  "Transit System",
  "Weather Station",
  "Capitol Building",
  "City Hall",
  "Consulate & Embassy",
  "Courthouse",
  "Fire Station",
  "Military Base",
  "Police Station",
  "Post Office",
  "Prison & Correctional Facility",
  "Town Hall",
  "Apartment & Condo Building",
  "Castle",
  "Dorm",
  "Fort",
  "Home",
  "Palace",
  "Stately Home",
  "Campus Building",
  "Light Rail Station",
  "Railway Station",
  "Subway Station"
];

const category_shopping = [
  "Shopping & Retail",
  "Camera Store",
  "Antique Store",
  "Apparel & Clothing",
  "Accessories",
  "Bags & Luggage Store",
  "Hat Store",
  "Jewelry & Watches Store",
  "Sunglasses & Eyewear Store",
  "Clothing Store",
  "Bridal Shop",
  "Baby & Children's Clothing Store",
  "Costume Shop",
  "Lingerie & Underwear Store",
  "Maternity & Nursing Clothing Store",
  "Men's Clothing Store",
  "Footwear Store",
  "Sportswear Store",
  "Swimwear Store",
  "Women's Clothing Store",
  "Arts & Crafts Store",
  "Auction House",
  "Beauty Store",
  "Cosmetics Store",
  "Beauty Supply Store",
  "Wig Store",
  "Big Box Retailer",
  "Boutique Store",
  "Collectibles Store",
  "Cultural Gifts Store",
  "Department Store",
  "Discount Store",
  "Duty-Free Shop",
  "Movie & Music Store",
  "E-Cigarette Store",
  "Educational Supply Store",
  "Electronics Store",
  "Audio Visual Equipment Store",
  "Computer Store",
  "Fabric Store",
  "Fireworks Retailer",
  "Flea Market",
  "Gift Shop",
  "Glass & Mirror Shop",
  "Gun Store",
  "Hobby Store",
  "Home & Garden Store",
  "Appliance Store",
  "Awning Supplier",
  "Blinds & Curtains Store",
  "Building Material Store",
  "Cabinet & Countertop Store",
  "Carpet & Flooring Store",
  "Fireplace Store",
  "Furniture Store",
  "Garden Center",
  "Hardware Store",
  "Home Theater Store",
  "Home Goods Store",
  "Lighting Store",
  "Mattress Store",
  "Nurseries & Gardening Store",
  "Lottery Retailer",
  "Mattress Wholesaler",
  "Mobile Phone Shop",
  "Musical Instrument Store",
  "Newsstand",
  "Night Market",
  "Office Equipment Store",
  "Outlet Store",
  "Moving Supply Store",
  "Party Supply & Rental Shop",
  "Carnival Supply Store",
  "Pawn Shop",
  "Pet Store",
  "Aquatic Pet Store",
  "Reptile Pet Store",
  "Pop-Up Shop",
  "Rent to Own Store",
  "Restaurant Supply Store",
  "Retail Company",
  "Seasonal Store",
  "Shopping Mall",
  "Shopping Service",
  "Souvenir Shop",
  "Sporting Goods Store",
  "Archery Shop",
  "Bicycle Shop",
  "Fishing Store",
  "Mountain Biking Shop",
  "Outdoor Equipment Store",
  "Skate Shop",
  "Ski & Snowboard Shop",
  "Surf Shop",
  "Outdoor & Sporting Goods Company",
  "Thrift & Consignment Store",
  "Tobacco Store",
  "Bookstore",
  "College / University Bookstore",
  "Comic Bookstore",
  "Independent Bookstore",
  "Religious Bookstore",
  "Toy Store",
  "Trophies & Engraving Shop",
  "Video Game Store",
  "Vintage Store",
  "Wholesale & Supply Store",
  "Other",
  "Brand",
  "App Page",
  "Baby Goods/Kids Goods",
  "Bags/Luggage",
  "Board Game",
  "Building Materials",
  "Camera/Photo",
  "Cars",
  "Clothing (Brand)",
  "Commercial Equipment",
  "Brand/Company Type",
  "Computers (Brand)",
  "Pharmaceuticals",
  "Electronics",
  "Furniture",
  "Games/Toys",
  "Health/Beauty",
  "Household Supplies",
  "Jewelry/Watches",
  "Musical Instrument",
  "Patio/Garden",
  "Pet Supplies",
  "Phone/Tablet",
  "Product/Service",
  "Product Type",
  "Software",
  "Tools/Equipment",
  "Appliances",
  "Home Decor",
  "Kitchen/Cooking",
  "Office Supplies",
  "Video Game",
  "Vitamins/Supplements",
  "Wine/Spirits",
  "Bags & Luggage Company",
  "Clothing Company",
  "Apparel Distributor",
  "Jewelry Wholesaler",
  "Jewelry & Watches Company",
  "Textile Company",
  "Florist",
  "Glass Blower",
  "Sewing & Alterations",
  "Shoe Repair Shop",
  "Medical Cannabis Dispensary",
  "Automotive, Aircraft & Boat",
  "Motor Vehicle Company",
  "Automotive Manufacturer",
  "Motorcycle Manufacturer",
  "Automotive Dealership",
  "Aircraft Dealership",
  "ATV Dealership",
  "Automotive Wholesaler",
  "Boat Dealership",
  "Car Dealership",
  "Commercial Truck Dealership",
  "Golf Cart Dealership",
  "Motorcycle Dealership",
  "Recreational Vehicle Dealership",
  "Trailer Dealership",
  "Automotive Store",
  "Automotive Parts Store",
  "Car Stereo Store",
  "Marine Supply Store",
  "Motorsports Store",
  "Aviation Repair Station",
  "Avionics Shop",
  "Candy Store",
  "Wine, Beer & Spirits Store",
  "Homebrew Supply Store"
];

const category_things_to_do = [
  "Arts & Entertainment",
  "Adult Entertainment Club",
  "Amusement & Theme Park",
  "Water Park",
  "Aquarium",
  "Arcade",
  "Art Gallery",
  "Betting Shop",
  "Bingo Hall",
  "Casino",
  "Circus",
  "Escape Game Room",
  "Haunted House",
  "Karaoke",
  "Movie Theater",
  "Drive-In Movie Theater",
  "Pool & Billiard Hall",
  "Race Track",
  "Salsa Club",
  "Performance & Event Venue",
  "Amphitheater",
  "Auditorium",
  "Comedy Club",
  "Jazz & Blues Club",
  "Live Music Venue",
  "Opera House",
  "Performance Art Theatre",
  "Museum",
  "Art Museum",
  "Asian Art Museum",
  "Cartooning Museum",
  "Contemporary Art Museum",
  "Costume Museum",
  "Decorative Arts Museum",
  "Design Museum",
  "Modern Art Museum",
  "Photography Museum",
  "Textile Museum",
  "Aviation Museum",
  "Children's Museum",
  "History Museum",
  "Civilization Museum",
  "Community Museum",
  "Science Museum",
  "Computer Museum",
  "Observatory",
  "Planetarium",
  "Sports Museum",
  "Zoo",
  "Petting Zoo",
  "Wildlife Sanctuary",
  "Specialty School",
  "Aviation School",
  "Bartending School",
  "Computer Training School",
  "Cooking School",
  "Cosmetology School",
  "Dance School",
  "Driving School",
  "First Aid Class",
  "Flight School",
  "Language School",
  "Massage School",
  "Music Lessons & Instruction School",
  "Nursing School",
  "Trade School",
  "Traffic School",
  "Winery/Vineyard",
  "Astrologist & Psychic",
  "Massage Therapist",
  "Medical Spa",
  "Meditation Center",
  "Sports & Recreation",
  "Sports & Recreation Venue",
  "Archery Range",
  "ATV Recreation Park",
  "Badminton Court",
  "Baseball Field",
  "Basketball Court",
  "Batting Cage",
  "Bowling Alley",
  "Disc Golf Course",
  "Driving Range",
  "Equestrian Center",
  "Fencing Club",
  "Flyboarding Center",
  "Go-Kart Track",
  "Golf Course & Country Club",
  "Gun Range",
  "Gymnastics Center",
  "Hang Gliding Center",
  "Hockey Field / Rink",
  "Horseback Riding Center",
  "Ice Skating Rink",
  "Kiteboarding Center",
  "Laser Tag Center",
  "Miniature Golf Course",
  "Paddleboarding Center",
  "Paintball Center",
  "Racquetball Court",

  "Rafting/Kayaking Center",
  "Recreation Center",
  "Rock Climbing Gym",
  "Rodeo",
  "Roller Skating Rink",
  "Rugby Pitch",
  "Scuba Diving Center",
  "Shooting/Hunting Range",
  "Skateboard Park",
  "Ski Resort",
  "Skydiving Center",
  "Soccer Field",
  "Fitness Venue",
  "Boxing Studio",
  "Cycling Studio",
  "Dance Studio",
  "Fitness Boot Camp",
  "Gym/Physical Fitness Center",
  "Martial Arts School",
  "Pilates Studio",
  "Tai Chi Studio",
  "Yoga Studio",
  "Squash Court",
  "Public Swimming Pool",
  "Tennis Court",
  "Volleyball Court",
  "Sports & Fitness Instruction",
  "Boat / Sailing Instructor",
  "Coach",
  "Golf Instructor",
  "Horse Riding School",
  "Fitness Trainer",
  "Scuba Instructor",
  "Ski & Snowboard School",
  "Swimming Instructor",
  "Rental Shop",
  "ATV Rental",
  "Bike Rental",
  "Boat Rental",
  "Canoe & Kayak Rental",
  "Car Rental",
  "Exotic Car Rental",
  "Jet Ski Rental",
  "Scooter Rental",
  "Trailer  Rental",
  "Truck Rental",
  "Transportation Service",
  "Airport Shuttle Service",
  "Charter Bus Service",
  "Limo Service",
  "Private Plane Charter",
  "Rideshare Service",
  "School Transportation Service",
  "Taxi Service",
  "Bus Line",
  "Cruise Line",
  "Boat/Ferry Company",
  "Travel Compan",
  "Tour Agency",
  "Architectural Tour Agency",
  "Art Tour Agency",
  "Boat Tour Agency",
  "Bus Tour Agency",
  "Eco Tour Agency",
  "Food Tour Agency",
  "Historical Tour Agency",
  "Horse-Drawn Carriage Service",
  "Hot Air Balloon Tour Agency",
  "Pedicab Service",
  "Sightseeing Tour Agency",
  "Tour Guide",
  "Travel Agency",
  "Cruise Agency",
  "Event",
  "Festival",
  "School Fundraiser",
  "Sports Event",
  "Just For Fun",
  "Farmers Market",
  "Grocery Store",
  "Ethnic Grocery Store",
  "Fish Market",
  "Fruit & Vegetable Store",
  "Health Food Store",
  "Organic Grocery Store",
  "Specialty Grocery Store",
  "Supermarket",
  "Wholesale Grocer",
  "Beauty, Cosmetic & Personal Care",
  "Barber Shop",
  "Beauty Salon",
  "Hair Salon",
  "Nail Salon",
  "Tanning Salon",
  "Hair Removal Service",
  "Laser Hair Removal Service",
  "Sugaring Service",
  "Threading Service",
  "Waxing Service",
  "Hair Replacement Service",
  "Hair Extensions Service",
  "Image Consultant",
  "Makeup Artist",
  "Skin Care Service",
  "SPA",
  "Aromatherapy Service",
  "Day Spa",
  "Health Spa",
  "Massage Service",
  "Onsen",
  "Beauty Supplier",
  "Tattoo & Piercing Shop",
  "Balloonport"
];

module.exports = {
  category_bar: category_bar,
  category_cafe: category_cafe,
  category_geographical_places: category_geographical_places,
  category_hotel: category_hotel,
  category_other: category_other,
  category_places_to_visit: category_places_to_visit,
  category_restaurant: category_restaurant,
  category_shopping: category_shopping,
  category_things_to_do: category_things_to_do
};
